#!/bin/sh

FILE_TYPE=$(file -b $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS|awk '{ print $1}')
MIME_TYPE=$(file -b $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)


if [ "$FILE_TYPE" != ".exe" ]; then
	 zenity  --error --title "File error" --text "$1 is not a Windows package.\nIt is reported as: $MIME_TYPE ($FILE_TYPE)" 2>&1
         exit -1;
else

wine $@

fi

